### ISSUE TITLE
Bug: Betreuer ohne Mitglied zu sein in einem Team

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#60]
Hallo @andreasrueedlinger 

Mir ist grad etwas aufgefallen: Wenn ein Betreur nicht im Team ist, des Athleten dann knallts im Endpoint `api/configuration/{id}`:
```
[2017-12-01 14:06:11.856] [ERROR] [default] - TypeError: Cannot read property 'reduce' of null
    at Function.flattenTree (/Users/yannisgu/s/tpak/code/server/dist/common/utils.js:22:25)
    at DiaryConfigurationService.<anonymous> (/Users/yannisgu/s/tpak/code/server/dist/modules/diary-configuration/services/diary-configuration.service.js:162:75)
    at Generator.next (<anonymous>)
    at /Users/yannisgu/s/tpak/code/server/dist/modules/diary-configuration/services/diary-configuration.service.js:19:71
    at Promise (<anonymous>)
    at __awaiter (/Users/yannisgu/s/tpak/code/server/dist/modules/diary-configuration/services/diary-configuration.service.js:15:12)
    at DiaryConfigurationService.mergeSecondaryAssociationsConfiguration (/Users/yannisgu/s/tpak/code/server/dist/modules/diary-configuration/services/diary-configuration.service.js:161:16)
    at DiaryConfigurationService.<anonymous> (/Users/yannisgu/s/tpak/code/server/dist/modules/diary-configuration/services/diary-configuration.service.js:57:28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yannisgu/s/tpak/code/server/dist/modules/diary-configuration/services/diary-configuration.service.js:16:58)
```
## Steps to reproduce
0. Einloggen als erich9
0. Im TTB "Annemie Meißner" auswählen

**Comment by andreasrueedlinger** [comment]
@yannisgu das Problem ist nicht, dass Betreuer nicht in diesem Team ist, sondern, dass bei der Athletin der ausgewählte Verband auf NULL gesetzt ist. Auch bei Verbänden <> swiss orienteering wirds wohl einen Fehler geben.
Soll ich den Fall abfangen mit einer leeren Config als Fallback?

**Comment by andreasrueedlinger** [comment]
siehe https://github.com/t-pak/code/pull/102
