### ISSUE TITLE
Bug-Sammlung T-Pak 5.0.0

### ISSUE THREAD

**Issue by andreasrueedlinger** [t-pak/issues#93]
### Patch 5.0.1
- [x] Registrieren/Aktivieren Labels bei Registrierung sind bei den Buttons vertauscht
- [x] mark as read bei access notifications funktioniert nicht
- [x] betreuer: eigene ansicht auf dashboard auch wenn kein athlet!
- [x] IE11 Bug: Login Dialog wird nicht geöffnet, `Error: StaticInjectorError[n -> function(){this.role=\"dialog....`
- [x] IE11 unterstützt `[].includes` nicht
- [x] keine Statistiken anfragen wenn kein Athlet ausgewählt ist, siehe Bug [2018-11-04T00:16:48.390] [ERROR] default
- [x] Jemand hat es geschafft, Einheitenteile doppelt hinzuzufügen. Wie schafft man das bzw. was haben wir nicht abgefangen? Da nicht reproduzierbar bei mir, habe ich einen "Fix-guess" eingecheckt.
- [x] Trainings mit Einheit können nicht gelöscht werden, wenn ein Teilnehmer Einheit manuell bearbeitet hat. Auf prod gefixt mit `ON DELETE SET NULL` auf foreign key. TODO: als migration dokumentieren
- [x] Speichern Buttons können zweimal hintereinander gedrückt werden => meist Fehler wegen Duplicate entry oder halt 2 Trainings. Lösung: button disabeln während speichern
- [x] Fehler Tageswerte laden wenn Trainingseinheit invalid date hat, siehe [2018-11-04T21:49:18.607] [ERROR] default
- [x] Kontaktformular Label success fehlt und form reset nach submit
- [x] Fragment scroll error, [2018-11-03T20:11:49.626] [ERROR] client
- [x] check for undefined life parameters in `getUnits`, [2018-11-04T20:21:39.361] [ERROR] client

### Patch 5.0.2
- [x] logout auf user settings page fürht zu userRelations = null und Fehler
- [x] Monatszyklus angewählt in Statistik, Wechsel zu männlich führt zu Fehler
- [x] Cannot read property 'icon' of null??
- [x] IE Meldung: not fully supported!
- [x] loading undefined user in analysis
- [x] Einheitenteile/Trainingsarten von früher werden nicht mehr unterstützt bzw. nicht angezeigt in Statistik (va. Kraft, da dort viele Einheitenteile entfernt wurden)
- [x] Geplantes Training von angemeldetem Training verschwindet nach einige Tagen

### Patch 5.0.3
- [x] Sidenav in Safari (Athleten Auswahl, etc.) oberster Teil unter Balken versteckt
- [x] Error wenn keine Anmeldeart ausgewählt
- [x] event entries edit bug wenn default status gesetzt
- [x] fix bug wenn athlete in analysis/diary preferences, auf den kein Zugriff mehr

### Patch 5.0.4
- [x] UserAccess Bug: User, die nur Gruppentrainer sind haben kein Zugriff auf Verbandsdaten (und so auch config die für Gruppentermine benötigt wird)
- [ ] Android 4.4 Promise Bug in Zone (https://github.com/angular/zone.js/issues/1078)
- [ ] Fehler in Dokumentenanzeige wenn Laden fehlschlägt

**Comment by andreasrueedlinger** [comment]
Häufig auftretend, wenn Browser html Cached und alte Files laden will:
```
[2018-11-03T19:29:07.555] [ERROR] client - {
  "errorMessage": "{ [Error: Loading chunk 5 failed.\n(error: https://www.t-pak.ch/5.c8453bb81d5ec2be5dd4.js)]\n  type: 'error',\n  request: 'https://www.t-pak.ch/5.c8453bb81d5ec2be5dd4.js' }",
  "url": "/main",
  "userState": {
    "loggedIn": false
  }
}
```

**Comment by andreasrueedlinger** [comment]
Ungeklärt:
```
[2018-11-03T19:44:18.234] [ERROR] client - {
  "errorMessage": "[Error: StaticInjectorError[n -> function(){this.role=\"dialog\",this.panelClass=\"\",this.hasBackdrop=!0,this.backdropClass=\"\",this.disableClose=!1,this.width=\"\",this.height=\"\",this.maxWidth=\"80vw\",this.data=null,this.ariaDescribedBy=null,this.ariaLabel=null,this.autoFocus=!0,this.closeOnNavigation=!0}]: \n  StaticInjectorError(Platform: core)[n -> function(){this.role=\"dialog\",this.panelClass=\"\",this.hasBackdrop=!0,this.backdropClass=\"\",this.disableClose=!1,this.width=\"\",this.height=\"\",this.maxWidth=\"80vw\",this.data=null,this.ariaDescribedBy=null,this.ariaLabel=null,this.autoFocus=!0,this.closeOnNavigation=!0}]: \n    NullInjectorError: No provider for function(){this.role=\"dialog\",this.panelClass=\"\",this.hasBackdrop=!0,this.backdropClass=\"\",this.disableClose=!1,this.width=\"\",this.height=\"\",this.maxWidth=\"80vw\",this.data=null,this.ariaDescribedBy=null,this.ariaLabel=null,this.autoFocus=!0,this.closeOnNavigation=!0}!]",
  "url": "/main",
  "userState": {
    "loggedIn": false
  }
}
```

**Comment by andreasrueedlinger** [comment]
Ungeklärt:
```
[2018-11-03T20:11:49.626] [ERROR] client - {
  "errorMessage": "{ [Error: Uncaught (in promise): EmptyError: no elements in sequence]\n  rejection: [EmptyError: no elements in sequence],\n  promise: \n   { __zone_symbol__state: 0,\n     __zone_symbol__value: [EmptyError: no elements in sequence] },\n  zone: \n   { _properties: { isAngularZone: true },\n     _parent: \n      { _properties: {},\n        _parent: null,\n        _name: '<root>',\n        _zoneDelegate: [Object] },\n     _name: 'angular',\n     _zoneDelegate: \n      { _taskCounts: [Object],\n        zone: [Circular],\n        _parentDelegate: [Object],\n        _forkZS: null,\n        _forkDlgt: null,\n        _forkCurrZone: [Object],\n        _interceptZS: null,\n        _interceptDlgt: null,\n        _interceptCurrZone: [Object],\n        _invokeZS: [Object],\n        _invokeDlgt: [Object],\n        _invokeCurrZone: [Circular],\n        _handleErrorZS: [Object],\n        _handleErrorDlgt: [Object],\n        _handleErrorCurrZone: [Circular],\n        _scheduleTaskZS: [Object],\n        _scheduleTaskDlgt: [Object],\n        _scheduleTaskCurrZone: [Circular],\n        _invokeTaskZS: [Object],\n        _invokeTaskDlgt: [Object],\n        _invokeTaskCurrZone: [Circular],\n        _cancelTaskZS: [Object],\n        _cancelTaskDlgt: [Object],\n        _cancelTaskCurrZone: [Circular],\n        _hasTaskZS: [Object],\n        _hasTaskDlgt: [Object],\n        _hasTaskDlgtOwner: [Circular],\n        _hasTaskCurrZone: [Circular] } },\n  task: \n   { _zone: \n      { _properties: [Object],\n        _parent: [Object],\n        _name: 'angular',\n        _zoneDelegate: [Object] },\n     runCount: 0,\n     _zoneDelegates: null,\n     _state: 'notScheduled',\n     type: 'microTask',\n     source: 'Promise.then',\n     data: \n      { __zone_symbol__state: 0,\n        __zone_symbol__value: [EmptyError: no elements in sequence] },\n     scheduleFn: undefined,\n     cancelFn: null,\n     callback: [Function],\n     invoke: [Function] } }",
  "url": "/training/diary/list/month/2018-11-03",
  "userState": {
    "loggedIn": true,
    "userId": 1877
  }
}
```

**Comment by andreasrueedlinger** [comment]
Versuch von Matthias Birrer automatisch auf die T-Pak Daten zuzugreifen:
```
[2018-11-04T09:04:13.714] [ERROR] default - {
  "error": {
    "fields": {
      "user": {
        "message": "invalid float number",
        "value": ""
      }
    },
    "message": "An error occurred during the request.",
    "name": "ValidateError",
    "status": 400
  },
  "request": {
    "method": "GET",
    "url": "/activities/2018-11-03%2008:04:16%20UTC/2018-11-04?user=&X-Auth-Token=*****",
    "headers": {
      "host": "localhost:63717",
      "accept-encoding": "gzip,deflate,identity",
      "accept": "*/*",
      "user-agent": "Mechanize/2.7.6 Ruby/2.5.1p57 (http://github.com/sparklemotion/mechanize/)",
      "accept-charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7",
      "accept-language": "en-us,en;q=0.5",
      "x-forwarded-proto": "https",
      "x-forwarded-https": "on",
      "x-forwarded-port": "443",
      "x-ssl-cipher": "TLSv1.2/DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD",
      "x-forwarded-for": "178.38.77.200, 178.38.77.200",
      "x-forwarded-host": "www.t-pak.ch",
      "x-forwarded-server": "tpak.rasalhague.uberspace.de",
      "connection": "Keep-Alive"
    },
    "trailers": {},
    "params": {},
    "query": {
      "user": "",
      "X-Auth-Token": "*****"
    },
    "body": {},
    "httpVersion": "1.1",
    "ip": "::1",
    "protocol": "http",
    "secure": false,
    "xhr": false,
    "hostname": "localhost",
    "originalUrl": "/activities/2018-11-03%2008:04:16%20UTC/2018-11-04?user=&X-Auth-Token=****"
  }
}
```
Auth tokens entfernt

**Comment by andreasrueedlinger** [comment]
Ungeklärt:
```
[2018-11-04T18:46:57.807] [ERROR] client - {
  "errorMessage": "[TypeError: Cannot read property 'icon' of null]",
  "url": "/training/activity/new;date=2018-11-20/form",
  "userState": {
    "loggedIn": true,
    "userId": 1938
  }
}
```

**Comment by andreasrueedlinger** [comment]
Diverse Statistik-Bugs:
```
[2018-11-04T20:21:39.361] [ERROR] client - {
  "errorMessage": "{ [TypeError: undefined is not an object (evaluating 'o.config')]\n  line: 1,\n  column: 1392409,\n  sourceURL: 'https://www.t-pak.ch/main.9fc13e492f424f94dc32.js' }",
  "url": "/analysis",
  "userState": {
    "loggedIn": true,
    "userId": 2195
  }
}
```

```
[2018-11-04T21:36:55.488] [ERROR] client - {
  "errorMessage": "[TypeError: Cannot read property 'userId' of undefined]",
  "url": "/analysis",
  "userState": {
    "loggedIn": true,
    "userId": 1251
  }
}
```

**Comment by andreasrueedlinger** [comment]
???
```
[2018-11-04T22:08:21.314] [ERROR] default - {
  "error": {
    "message": "ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction",
    "name": "QueryFailedError",
    "status": 500,
    "stack": "QueryFailedError: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction\n    at new QueryFailedError (/var/www/virtual/tpak/apps/tpak-prod/20181103_154719/server/node_modules/typeorm/error/QueryFailedError.js:27:28)\n    at Query._callback (/var/www/virtual/tpak/apps/tpak-prod/20181103_154719/server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:223:45)\n    at Query.Sequence.end (/var/www/virtual/tpak/apps/tpak-prod/20181103_154719/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)\n    at Query.ErrorPacket (/var/www/virtual/tpak/apps/tpak-prod/20181103_154719/server/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)\n    at Protocol._parsePacket (/var/www/virtual/tpak/apps/tpak-prod/20181103_154719/server/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/var/www/virtual/tpak/apps/tpak-prod/20181103_154719/server/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/var/www/virtual/tpak/apps/tpak-prod/20181103_154719/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/var/www/virtual/tpak/apps/tpak-prod/20181103_154719/server/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)"
  },
  "request": {
    "method": "PUT",
    "url": "/activities/1022385",
    "headers": {
      "host": "localhost:63717",
      "content-type": "application/json",
      "origin": "https://www.t-pak.ch",
      "x-auth-token": "*****",
      "accept-encoding": "gzip, deflate",
      "accept": "application/json, text/plain, */*",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15",
      "referer": "https://www.t-pak.ch/training/activity/edit/1022385/form",
      "accept-language": "de-ch",
      "x-forwarded-proto": "https",
      "x-forwarded-https": "on",
      "x-forwarded-port": "443",
      "x-ssl-cipher": "TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD",
      "x-forwarded-for": "185.74.125.39, 185.74.125.39",
      "x-forwarded-host": "www.t-pak.ch",
      "x-forwarded-server": "tpak.rasalhague.uberspace.de",
      "connection": "Keep-Alive",
      "content-length": "337"
    },
    "trailers": {},
    "params": {},
    "query": {},
    "body": {
      "id": 1022385,
      "activityDetails": [],
      "activityTypeId": 25,
      "completed": true,
      "date": "2018-01-02",
      "duration": 80,
      "intensityRanges": [
        {
          "intensityRangeId": 5,
          "duration": 80
        }
      ],
      "isTemplate": false,
      "nextId": 1022386,
      "parameters": [],
      "planned": false,
      "previousId": 1022384,
      "subActivities": [
        {
          "subActivityTypeId": 25,
          "duration": 80
        }
      ],
      "userId": 2129,
      "title": "NWK"
    },
    "httpVersion": "1.1",
    "ip": "::1",
    "protocol": "http",
    "secure": false,
    "xhr": false,
    "hostname": "localhost",
    "originalUrl": "/activities/1022385",
    "session": {
      "token": "*****",
      "expirationDate": "2018-12-04T21:07:30.643Z",
      "longSession": true,
      "created": "2018-11-04T20:09:42.000Z",
      "user": ****
    }
  }
}
```
Token und User entfernt

**Comment by andreasrueedlinger** [comment]
> bei "benutzerprofil" und "Freigabe deines TTB für Trainer" wenn ich den Radiobutton ändere (zugiff, kein zugriff) kommt die Aufforderung (als blauer Balken) zu speichern. Es hat aber keine Speichern zeichen und ist glaube ich auch nicht nötig...

WAD, ???

**Comment by jeggi87** [comment]
![image001](https://user-images.githubusercontent.com/25025643/48087491-b981c600-e1ff-11e8-8605-ef081e36df92.png)

Begriff nicht übersetzt?

**Comment by jeggi87** [comment]
> > bei "benutzerprofil" und "Freigabe deines TTB für Trainer" wenn ich den Radiobutton ändere (zugiff, kein zugriff) kommt die Aufforderung (als blauer Balken) zu speichern. Es hat aber keine Speichern zeichen und ist glaube ich auch nicht nötig...
> 
> WAD, @jeggi87 ???

ist erledigt, funktioniert.

**Comment by jeggi87** [comment]
Danke für die Antwort. Mit petschu@gmail.ch funktioniert zwar der Link "Passwort vergessen" / "Passwort zurücksetzen". Allerdings habe ich gar keine Mailadresse mit gmail.ch, sondern nur mit gmail.com. Das muss wohl bei der Registrierung ein Tippfehler gewesen sein. Gibt es trotzdem einen Weg mein altes Konto wieder zu reaktivieren oder soll ich mich einfach neu registrieren?

**Comment by jeggi87** [comment]
Liebe Kollegin, lieber Kollege Ich habe vor langer Zeit einen Account unter haefeli@itp.unibe.ch bei euch erÃ¶ffnet. Auf diese Emailadresse habe ich keinen Zugriff mehr, ihr schickt aber weiterhin Newsletter auf diese Adresse. Der Sysadmin von itp.unibe.ch bittet mich, den Newsletter abzustellen oder umzuleiten. Darf ich euch bitten, die Adresse haefeli@itp.unibe.ch aus eurer Liste zu entfernen? Danke. Viele GrÃ¼sse Christoph
http://www.t-pak.ch

**Comment by andreasrueedlinger** [comment]
@jeggi87 bitte keine Supportanfragen hier. Und keine persönlichen Daten, dieser Teil von github ist öffentlich!

**Comment by andreasrueedlinger** [comment]
```
[2018-11-06T17:45:33.893] [ERROR] client - {
  "errorMessage": "{ [TypeError: undefined is not an object (evaluating 'fl(t=this._element,\"\").trim')]\n  line: 1,\n  column: 2700152,\n  sourceURL: 'https://www.t-pak.ch/main.9fc13e492f424f94dc32.js' }",
  "url": "/main",
  "userState": {
    "loggedIn": false
  }
}
```
Ursache: https://github.com/angular/angular/issues/24094

Wohl auch: 
```
[2018-11-12T07:00:51.021] [ERROR] client - {
  "error": {
    "errorMessage": "[TypeError: Cannot call method 'trim' of undefined]",
    "url": "/main",
    "userState": {
      "loggedIn": false
    }
  },
```

**Comment by andreasrueedlinger** [comment]
Unklar:
```
[2018-11-06T17:55:12.651] [ERROR] client - {
  "errorMessage": "[TypeError: Unable to get property 'userId' of undefined or null reference]",
  "url": "/training/diary/list/month/today",
  "userState": {
    "loggedIn": true,
    "userId": 466
  }
}
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-08T22:00:03.397] [ERROR] client - {
  "error": {
    "errorMessage": "{ [TypeError: null is not an object (evaluating 'a.unit')]\n  line: 1,\n  column: 1390020,\n  sourceURL: 'https://www.t-pak.ch/main.fd8746240b415839db40.js' }",
    "url": "/analysis",
    "userState": {
      "loggedIn": true,
      "userId": 1113
    }
  },
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-08T21:48:52.173] [ERROR] client - {
  "error": {
    "errorMessage": "[TypeError: Cannot read property 'icon' of null]",
    "url": "/training/activity/new;date=2018-11-07/form",
    "userState": {
      "loggedIn": true,
      "userId": 903
    }
  },
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-08T19:37:34.011] [ERROR] client - {
  "error": {
    "errorMessage": "[TypeError: Cannot read property 'type' of null]",
    "url": "/main",
    "userState": {
      "loggedIn": false
    }
  },
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-08T17:39:08.570] [ERROR] client - {
  "error": {
    "errorMessage": "[TypeError: this.userRelations is null]",
    "url": "/main",
    "userState": {
      "loggedIn": false
    }
  },
```

**Comment by andreasrueedlinger** [comment]
Still here:
```
[2018-11-08T19:37:26.846] [ERROR] default - {
  "error": {
    "fields": {
      "id": {
        "message": "invalid float number",
        "value": "undefined"
      }
    },
    "message": "An error occurred during the request.",
    "name": "ValidateError",
    "status": 400
  },
  "request": {
    "method": "GET",
    "url": "/users/undefined",
    "headers": {
      "host": "localhost:63717",
      "accept": "application/json, text/plain, */*",
      "x-auth-token": "5f4dba9a-6e04-40f8-a4ff-278e7e13aaa6",
      "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
      "referer": "https://www.t-pak.ch/analysis",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "de-CH,de;q=0.9,en;q=0.8",
      "x-forwarded-proto": "https",
      "x-forwarded-https": "on",
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-07T15:45:01.500] [ERROR] client - {
  "errorMessage": "[TypeError: undefined is not a function]",
  "url": "/dashboard",
  "userState": {
    "loggedIn": true,
    "userId": 2154
  }
}
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-10T08:32:18.701] [ERROR] client - {
  "error": {
    "errorMessage": "[TypeError: Cannot read property 'length' of undefined]",
    "url": "/main",
    "userState": {
      "loggedIn": false
    }
  },
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-11T11:10:28.090] [ERROR] client - {
  "error": {
    "errorMessage": "{ headers: { normalizedNames: {}, lazyUpdate: null, headers: {} },\n  status: 0,\n  statusText: 'Unknown Error',\n  url: null,\n  ok: false,\n  name: 'HttpErrorResponse',\n  message: 'Http failure response for (unknown url): 0 Unknown Error',\n  error: { isTrusted: [Getter] } }",
    "url": "/analysis",
    "userState": {
      "loggedIn": true,
      "userId": 967
    }
  },
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-11T19:40:34.072] [ERROR] client - {
  "error": {
    "errorMessage": "[TypeError: Cannot read property 'focus' of undefined]",
    "url": "/training/diary/list/week/today",
    "userState": {
      "loggedIn": true,
      "userId": 722
    }
  },
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-12T07:53:02.610] [ERROR] client - {
  "error": {
    "errorMessage": "{ [Error: Uncaught (in promise): EmptyError: no elements in sequence]\n  rejection: [EmptyError: no elements in sequence],\n  promise: \n   { __zone_symbol__state: 0,\n     __zone_symbol__value: [EmptyError: no elements in sequence] },\n  zone: \n   { _properties: { isAngularZone: true },\n     _parent: \n      { _properties: {},\n        _parent: null,\n        _name: '<root>',\n        _zoneDelegate: [Object] },\n     _name: 'angular',\n     _zoneDelegate: \n      { _taskCounts: [Object],\n        zone: [Circular],\n        _parentDelegate: [Object],\n        _forkZS: null,\n        _forkDlgt: null,\n        _forkCurrZone: [Object],\n        _interceptZS: null,\n        _interceptDlgt: null,\n        _interceptCurrZone: [Object],\n        _invokeZS: [Object],\n        _invokeDlgt: [Object],\n        _invokeCurrZone: [Circular],\n        _handleErrorZS: [Object],\n        _handleErrorDlgt: [Object],\n        _handleErrorCurrZone: [Circular],\n        _scheduleTaskZS: [Object],\n        _scheduleTaskDlgt: [Object],\n        _scheduleTaskCurrZone: [Circular],\n        _invokeTaskZS: [Object],\n        _invokeTaskDlgt: [Object],\n        _invokeTaskCurrZone: [Circular],\n        _cancelTaskZS: [Object],\n        _cancelTaskDlgt: [Object],\n        _cancelTaskCurrZone: [Circular],\n        _hasTaskZS: [Object],\n        _hasTaskDlgt: [Object],\n        _hasTaskDlgtOwner: [Circular],\n        _hasTaskCurrZone: [Circular] } },\n  task: \n   { _zone: \n      { _properties: [Object],\n        _parent: [Object],\n        _name: 'angular',\n        _zoneDelegate: [Object] },\n     runCount: 0,\n     _zoneDelegates: null,\n     _state: 'notScheduled',\n     type: 'microTask',\n     source: 'Promise.then',\n     data: \n      { __zone_symbol__state: 0,\n        __zone_symbol__value: [EmptyError: no elements in sequence] },\n     scheduleFn: undefined,\n     cancelFn: null,\n     callback: [Function],\n     invoke: [Function] } }",
    "url": "/training/diary/list/week/today",
    "userState": {
      "loggedIn": true,
      "userId": 363
    }
  },
```
Jetzt noch mit stack:
```
"F@https://www.t-pak.ch/polyfills.161e36abf3ce8f3832bb.js:1:13743\nF@https://www.t-pak.ch/polyfills.161e36abf3ce8f3832bb.js:1:13293\nhttps://www.t-pak.ch/polyfills.161e36abf3ce8f3832bb.js:1:14523\nonInvokeTask@https://www.t-pak.ch/main.1c8b59da5d0e0d2c353b.js:1:321858\nrunTask@https://www.t-pak.ch/polyfills.161e36abf3ce8f3832bb.js:1:3939\nv@https://www.t-pak.ch/polyfills.161e36abf3ce8f3832bb.js:1:10977\ninvokeTask@https://www.t-pak.ch/polyfills.161e36abf3ce8f3832bb.js:1:9865\ny@https://www.t-pak.ch/polyfills.161e36abf3ce8f3832bb.js:1:20762\nb@https://www.t-pak.ch/polyfills.161e36abf3ce8f3832bb.js:1:20987"
```

**Comment by andreasrueedlinger** [comment]
https://github.com/angular/zone.js/issues/1078
```
[2018-11-12T20:34:11.660] [ERROR] client - {
  "error": {
    "errorMessage": "[TypeError: Property '__zone_symbol__then' of object [object Promise] is not a function]",
    "url": "/communication/trainings/9496",
    "userState": {
      "loggedIn": false
    }
  },
```

**Comment by andreasrueedlinger** [comment]
```
[2018-11-15T10:37:48.670] [ERROR] client - {
  "error": {
    "errorMessage": "{ [Error: Uncaught (in promise): EmptyError: no elements in sequence]
...
```
